version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./L1-edge/L1-edge.conf:/etc/L1-edge/L1-edge.conf:ro
      - ./Homepage:/var/www/home:ro
      - ./Authentification/frontend:/var/www/auth_frontend:ro
      - ./ServicePanel:/usr/share/L1-edge/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-root.rule=PathPrefix(`/`)
      - traefik.http.routers.web-root.entrypoints=web
      - traefik.http.routers.web-root.priority=1
      - traefik.http.services.web-root.loadbalancer.server.port=80

  backend:
    build: ./StoreMate/app
    env_file:
      - ./environments/storemate.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.api.priority=10
      - traefik.http.services.api.loadbalancer.server.port=8000

  auth_backend:
    build: ./Authentification/backend
    env_file:
      - environments/authentification.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.rule=PathPrefix(`/auth`)
      - traefik.http.routers.auth.entrypoints=web
      - traefik.http.routers.auth.priority=10
      - traefik.http.services.auth.loadbalancer.server.port=8081

  frontend:
    build: ./StoreMate/frontend-docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.store.rule=PathPrefix(`/storemate`)
      - traefik.http.routers.store.entrypoints=web
      - traefik.http.routers.store.priority=10
      - traefik.http.services.store.loadbalancer.server.port=5173