version = 4.2.0
archive_dir = /etc/letsencrypt/archive/prereact.ch
cert = /etc/letsencrypt/live/prereact.ch/cert.pem
privkey = /etc/letsencrypt/live/prereact.ch/privkey.pem
chain = /etc/letsencrypt/live/prereact.ch/chain.pem
fullchain = /etc/letsencrypt/live/prereact.ch/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = bc084b5b8f5686a20fbd607591c16e38
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
prereact.ch = /var/www/certbot
www.prereact.ch = /var/www/certbot
